In [1]:
import pandas as pd
data=pd.read_csv("C:/Users/George/Desktop/test/dataset_investing_stock_market.csv",encoding="ISO-8859-1", sep=';', header=None)
data

       0        1                                                  2
0     No  Classes                                               Text
1      1     GOOD  PARIS (Reuters) -French carmaker Renault (EPA:...
2      2      BAD  (Reuters) - Russia may face an "orchestrated" ...
3      3      BAD  European stock markets traded sharply lower Fr...
4      4      BAD  Swedish truck maker AB Volvo reported a surpri...
..   ...      ...                                                ...
96    96  NEUTRAL  Ralph Lauren Corp (NYSE:RL) shares declined 3....
97    97     GOOD  The news sent shares of Carnival up nearly 4% ...
98    98      BAD  First Solar stock (NASDAQ:FSLR) traded 3.6% lo...
99    99      BAD  While the $ amount of buybacks in 1Q was above...
100  100      BAD  Xponential Fitness Inc. (NYSE:XPOF) shares fel...

[101 rows x 3 columns]

In [2]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [3]:
data

       0        1                                                  2
0     No  Classes                                               Text
1      1     GOOD  PARIS (Reuters) -French carmaker Renault (EPA:...
2      2      BAD  (Reuters) - Russia may face an "orchestrated" ...
3      3      BAD  European stock markets traded sharply lower Fr...
4      4      BAD  Swedish truck maker AB Volvo reported a surpri...
..   ...      ...                                                ...
96    96  NEUTRAL  Ralph Lauren Corp (NYSE:RL) shares declined 3....
97    97     GOOD  The news sent shares of Carnival up nearly 4% ...
98    98      BAD  First Solar stock (NASDAQ:FSLR) traded 3.6% lo...
99    99      BAD  While the $ amount of buybacks in 1Q was above...
100  100      BAD  Xponential Fitness Inc. (NYSE:XPOF) shares fel...

[101 rows x 3 columns]

In [4]:
data[0].value_counts()

No     1
64     1
74     1
73     1
72     1
      ..
31     1
30     1
29     1
28     1
100    1
Name: 0, Length: 101, dtype: int64

In [5]:
data[1].value_counts()

GOOD       41
BAD        39
NEUTRAL    20
Classes     1
Name: 1, dtype: int64

In [6]:
data.rename(columns = {'0':'No', '1':'Classes', '2':'Text'}, inplace=True)

In [7]:
data

       0        1                                                  2
0     No  Classes                                               Text
1      1     GOOD  PARIS (Reuters) -French carmaker Renault (EPA:...
2      2      BAD  (Reuters) - Russia may face an "orchestrated" ...
3      3      BAD  European stock markets traded sharply lower Fr...
4      4      BAD  Swedish truck maker AB Volvo reported a surpri...
..   ...      ...                                                ...
96    96  NEUTRAL  Ralph Lauren Corp (NYSE:RL) shares declined 3....
97    97     GOOD  The news sent shares of Carnival up nearly 4% ...
98    98      BAD  First Solar stock (NASDAQ:FSLR) traded 3.6% lo...
99    99      BAD  While the $ amount of buybacks in 1Q was above...
100  100      BAD  Xponential Fitness Inc. (NYSE:XPOF) shares fel...

[101 rows x 3 columns]

In [8]:
data.rename(columns = {0:'No', 1:'Classes', 2:'Text'}, inplace=True)

In [9]:
data

      No  Classes                                               Text
0     No  Classes                                               Text
1      1     GOOD  PARIS (Reuters) -French carmaker Renault (EPA:...
2      2      BAD  (Reuters) - Russia may face an "orchestrated" ...
3      3      BAD  European stock markets traded sharply lower Fr...
4      4      BAD  Swedish truck maker AB Volvo reported a surpri...
..   ...      ...                                                ...
96    96  NEUTRAL  Ralph Lauren Corp (NYSE:RL) shares declined 3....
97    97     GOOD  The news sent shares of Carnival up nearly 4% ...
98    98      BAD  First Solar stock (NASDAQ:FSLR) traded 3.6% lo...
99    99      BAD  While the $ amount of buybacks in 1Q was above...
100  100      BAD  Xponential Fitness Inc. (NYSE:XPOF) shares fel...

[101 rows x 3 columns]

In [10]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
def remove_punctuation(text):
    punctuationfree="".join([i for i in text if i not in string.punctuation])
    return punctuationfree
data['clean_msg']=data['Text'].apply(lambda x:remove_punctuation(x))
data.head()

,No,Classes,Text,clean_msg
0,No,Classes,Text,Text
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...

In [12]:
data['msg_lower']=data['clean_msg'].apply(lambda x: x.lower())

In [13]:
data.head()

,No,Classes,Text,clean_msg,msg_lower
0,No,Classes,Text,Text,text
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...,paris reuters french carmaker renault eparena ...
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...,reuters russia may face an orchestrated defau...
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...,european stock markets traded sharply lower fr...
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...,swedish truck maker ab volvo reported a surpri...

In [14]:
import re
def tokenization(text):
    tokens = re.split('W+',text)
    return tokens
data['msg_tokenied']= data['msg_lower'].apply(lambda x: tokenization(x))

In [15]:
data.head()

,No,Classes,Text,clean_msg,msg_lower,msg_tokenied
0,No,Classes,Text,Text,text,[text]
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...,paris reuters french carmaker renault eparena ...,[paris reuters french carmaker renault eparena...
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...,reuters russia may face an orchestrated defau...,[reuters russia may face an orchestrated defa...
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...,european stock markets traded sharply lower fr...,[european stock markets traded sharply lower f...
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...,swedish truck maker ab volvo reported a surpri...,[swedish truck maker ab volvo reported a surpr...

In [16]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\George\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
import nltk
stopwords = nltk.corpus.stopwords.words('english')
stopwords[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [18]:
def remove_stopwords(text):
    output= [i for i in text if i not in stopwords]
    return output

In [19]:
data['no_stopwords']=data['msg_tokenied'].apply(lambda x:remove_stopwords(x))

In [20]:
def remove_stopwords(text):
    output= [i for i in text if i not in stopwords]
    return output
data['no_stopwords']=data['msg_tokenid'].apply(lambda x:remove_stopwords(x))

KeyError: 'msg_tokenid'

In [ ]:
data.drop('no_stopwords',inplace=True,axis=1)

In [ ]:
data.drop("msg_tokenid",inplace=True , axis=1)

In [21]:
data

,No,Classes,Text,clean_msg,msg_lower,msg_tokenied,no_stopwords
0,No,Classes,Text,Text,text,[text],[text]
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...,paris reuters french carmaker renault eparena ...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...,reuters russia may face an orchestrated defau...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...,european stock markets traded sharply lower fr...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...,swedish truck maker ab volvo reported a surpri...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...
...,...,...,...,...,...,...,...
96,96,NEUTRAL,Ralph Lauren Corp (NYSE:RL) shares declined 3....,Ralph Lauren Corp NYSERL shares declined 33 on...,ralph lauren corp nyserl shares declined 33 on...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...
97,97,GOOD,The news sent shares of Carnival up nearly 4% ...,The news sent shares of Carnival up nearly 4 i...,the news sent shares of carnival up nearly 4 i...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...
98,98,BAD,First Solar stock (NASDAQ:FSLR) traded 3.6% lo...,First Solar stock NASDAQFSLR traded 36 lower T...,first solar stock nasdaqfslr traded 36 lower t...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...
99,99,BAD,While the $ amount of buybacks in 1Q was above...,While the amount of buybacks in 1Q was above ...,while the amount of buybacks in 1q was above ...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...
100,100,BAD,Xponential Fitness Inc. (NYSE:XPOF) shares fel...,Xponential Fitness Inc NYSEXPOF shares fell 6 ...,xponential fitness inc nysexpof shares fell 6 ...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...

In [ ]:
import re

In [ ]:
def tokenization(text):
    tokens=re.split("[\s.,!?:;'\"-]+",text)
    return tokens
data['msg_tokenied']= data['msg_lower'].apply(lambda x: tokenization(x))

In [ ]:
data

In [ ]:
import nltk
stopwords=nltk.corpus.stopwords.words('english')
stopwords[0:10]

In [ ]:
def remove_stopwords(text):
    output=[i for i in text if i not in stopwords]
    return output

In [ ]:
data['no_stopwords']=data['msg_tokenied'].apply(lambda x:remove_stopwords(x))

In [ ]:
data

In [22]:
from nltk.stem.porter import PorterStemmer

In [23]:
porter_stemmer=PorterStemmer()

In [24]:
def stemming(text):
    stem_text=[porter_stemmer.stem(word) for word in text]
    return stem_text
data['msg_stemmed']=data['no_stopwords'].apply(lambda x:stemming(x))

In [25]:
def stemming(text):
    stem_text=[porter_stemmer.stem(word) for word in text]
    return stem_text
data['msg_stemmed']=data['no_stopwords'].apply(lambda x:stemming(x))

In [26]:
data.head()

,No,Classes,Text,clean_msg,msg_lower,msg_tokenied,no_stopwords,msg_stemmed
0,No,Classes,Text,Text,text,[text],[text],[text]
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...,paris reuters french carmaker renault eparena ...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...,reuters russia may face an orchestrated defau...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...,european stock markets traded sharply lower fr...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...,swedish truck maker ab volvo reported a surpri...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...

In [27]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

In [28]:
def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    return lemm_text
data['msg_lemmatized']=data['no_stopwords'].apply(lambda x:lemmatizer(x))

In [29]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\George\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [30]:
def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    return lemm_text
data['msg_lemmatized']=data['no_stopwords'].apply(lambda x:lemmatizer(x))

In [32]:
data['msg_lemmatized_string']=data['msg_lemmatized'].apply(lambda x: ' '.join(map(str, x)))

In [ ]:
str1 = ''.join(data['no_stopwords'][5])

In [ ]:
str1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(data[''])

In [33]:
data

,No,Classes,Text,clean_msg,msg_lower,msg_tokenied,no_stopwords,msg_stemmed,msg_lemmatized,msg_lemmatized_string
0,No,Classes,Text,Text,text,[text],[text],[text],[text],text
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...,paris reuters french carmaker renault eparena ...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,paris reuters french carmaker renault eparena ...
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...,reuters russia may face an orchestrated defau...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,reuters russia may face an orchestrated defau...
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...,european stock markets traded sharply lower fr...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,european stock markets traded sharply lower fr...
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...,swedish truck maker ab volvo reported a surpri...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,swedish truck maker ab volvo reported a surpri...
...,...,...,...,...,...,...,...,...,...,...
96,96,NEUTRAL,Ralph Lauren Corp (NYSE:RL) shares declined 3....,Ralph Lauren Corp NYSERL shares declined 33 on...,ralph lauren corp nyserl shares declined 33 on...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...,ralph lauren corp nyserl shares declined 33 on...
97,97,GOOD,The news sent shares of Carnival up nearly 4% ...,The news sent shares of Carnival up nearly 4 i...,the news sent shares of carnival up nearly 4 i...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...,the news sent shares of carnival up nearly 4 i...
98,98,BAD,First Solar stock (NASDAQ:FSLR) traded 3.6% lo...,First Solar stock NASDAQFSLR traded 36 lower T...,first solar stock nasdaqfslr traded 36 lower t...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...,first solar stock nasdaqfslr traded 36 lower t...
99,99,BAD,While the $ amount of buybacks in 1Q was above...,While the amount of buybacks in 1Q was above ...,while the amount of buybacks in 1q was above ...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...,while the amount of buybacks in 1q was above ...
100,100,BAD,Xponential Fitness Inc. (NYSE:XPOF) shares fel...,Xponential Fitness Inc NYSEXPOF shares fell 6 ...,xponential fitness inc nysexpof shares fell 6 ...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...,xponential fitness inc nysexpof shares fell 6 ...

In [ ]:
data.head()

In [ ]:
def remove_stopwords2(text):
    output= [i for i in text.split() if i not in stopwords]
    return output

In [ ]:
data['no_stopwords2']=data['msg_lower'].apply(lambda x:remove_stopwords2(x))

In [ ]:
data

In [ ]:
import gensim
from gensim.parsing.preprocessing import remove_stopwords, STOPWORDS
print(STOPWORDS)

In [ ]:
import spacy

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()

In [ ]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()
count_matrix = vectorizer.fit_transform(data['no_stopwords'][20])
count_array = count_matrix.toarray()
count_array

In [ ]:
vectorizer.fit(data['no_stopwords'][3])
print(vectorizer.vocabulary_)

In [ ]:
vectorizer = TfidfVectorizer()
matrix = vectorizer.fit_transform(data['no_stopwords'])
count_array = matrix.toarray()
data['count_array']=data['no_stopwords'].apply(lambda x:matrix)

In [ ]:
data.drop('count_array',inplace=True,axis=1)

In [ ]:
data

In [34]:
import texthero as hero

In [35]:
data['tfidf'] = hero.tfidf(data['msg_lemmatized_string'])

In [ ]:
data['msg_lemmatized']=data['msg_lemmatized'].apply(str)

In [36]:
data['tfidf'] = hero.tfidf(data['msg_lemmatized_string'],max_features=100)

In [ ]:
data['pca'] = hero.pca(data['tfidf'])
hero.scatterplot(
    data, 
    col='pca', 
    color='Classes', 
    title="PCA BBC Sport news"
)

In [ ]:
data['tfidf'] = (
    hero.tfidf(data['msg_lemmatized'], max_features=100)
)
data[["tfidf", "Classes"]].head(100)

In [38]:
import pandas as pd
from collections import Counter

In [40]:
data['BOW'] = data['msg_lemmatized_string'].apply(lambda x: Counter(x.split(" ")))

In [41]:
data

,No,Classes,Text,clean_msg,msg_lower,msg_tokenied,no_stopwords,msg_stemmed,msg_lemmatized,msg_lemmatized_string,tfidf,BOW
0,No,Classes,Text,Text,text,[text],[text],[text],[text],text,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'text': 1}
1,1,GOOD,PARIS (Reuters) -French carmaker Renault (EPA:...,PARIS Reuters French carmaker Renault EPARENA ...,paris reuters french carmaker renault eparena ...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,[paris reuters french carmaker renault eparena...,paris reuters french carmaker renault eparena ...,"[0.08086494559318308, 0.1562423604092894, 0.0,...","{'paris': 1, 'reuters': 1, 'french': 2, 'carma..."
2,2,BAD,"(Reuters) - Russia may face an ""orchestrated"" ...",Reuters Russia may face an orchestrated defau...,reuters russia may face an orchestrated defau...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,[reuters russia may face an orchestrated defa...,reuters russia may face an orchestrated defau...,"[0.0, 0.1882668330802365, 0.0, 0.0, 0.0, 0.0, ...","{'reuters': 1, '': 1, 'russia': 2, 'may': 1, '..."
3,3,BAD,European stock markets traded sharply lower Fr...,European stock markets traded sharply lower Fr...,european stock markets traded sharply lower fr...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,[european stock markets traded sharply lower f...,european stock markets traded sharply lower fr...,"[0.0, 0.17953640221812384, 0.04229591741854004...","{'european': 2, 'stock': 5, 'markets': 3, 'tra..."
4,4,BAD,Swedish truck maker AB Volvo reported a surpri...,Swedish truck maker AB Volvo reported a surpri...,swedish truck maker ab volvo reported a surpri...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,[swedish truck maker ab volvo reported a surpr...,swedish truck maker ab volvo reported a surpri...,"[0.0, 0.19899834242847333, 0.0, 0.0, 0.0, 0.06...","{'swedish': 2, 'truck': 5, 'maker': 1, 'ab': 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,NEUTRAL,Ralph Lauren Corp (NYSE:RL) shares declined 3....,Ralph Lauren Corp NYSERL shares declined 33 on...,ralph lauren corp nyserl shares declined 33 on...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...,[ralph lauren corp nyserl shares declined 33 o...,ralph lauren corp nyserl shares declined 33 on...,"[0.0, 0.08012331238639361, 0.0, 0.120550436078...","{'ralph': 3, 'lauren': 3, 'corp': 1, 'nyserl':..."
97,97,GOOD,The news sent shares of Carnival up nearly 4% ...,The news sent shares of Carnival up nearly 4 i...,the news sent shares of carnival up nearly 4 i...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...,[the news sent shares of carnival up nearly 4 ...,the news sent shares of carnival up nearly 4 i...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.18770781122895494,...","{'the': 5, 'news': 2, 'sent': 1, 'shares': 1, ..."
98,98,BAD,First Solar stock (NASDAQ:FSLR) traded 3.6% lo...,First Solar stock NASDAQFSLR traded 36 lower T...,first solar stock nasdaqfslr traded 36 lower t...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...,[first solar stock nasdaqfslr traded 36 lower ...,first solar stock nasdaqfslr traded 36 lower t...,"[0.1476547764675184, 0.213967226142571, 0.0, 0...","{'first': 1, 'solar': 2, 'stock': 2, 'nasdaqfs..."
99,99,BAD,While the $ amount of buybacks in 1Q was above...,While the amount of buybacks in 1Q was above ...,while the amount of buybacks in 1q was above ...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...,[while the amount of buybacks in 1q was above...,while the amount of buybacks in 1q was above ...,"[0.0, 0.36665557827010714, 0.0, 0.0, 0.0, 0.0,...","{'while': 2, 'the': 3, '': 4, 'amount': 1, 'of..."
100,100,BAD,Xponential Fitness Inc. (NYSE:XPOF) shares fel...,Xponential Fitness Inc NYSEXPOF shares fell 6 ...,xponential fitness inc nysexpof shares fell 6 ...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...,[xponential fitness inc nysexpof shares fell 6...,xponential fitness inc nysexpof shares fell 6 ...,"[0.0, 0.20441196102344955, 0.0, 0.153775164226...","{'xponential': 1, 'fitness': 1, 'inc': 1, 'nys..."

In [ ]:
data.head()

In [44]:
X=data['tfidf']

In [45]:
y=data['Classes']

In [46]:
X

0      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1      [0.08086494559318308, 0.1562423604092894, 0.0,...
2      [0.0, 0.1882668330802365, 0.0, 0.0, 0.0, 0.0, ...
3      [0.0, 0.17953640221812384, 0.04229591741854004...
4      [0.0, 0.19899834242847333, 0.0, 0.0, 0.0, 0.06...
                             ...
96     [0.0, 0.08012331238639361, 0.0, 0.120550436078...
97     [0.0, 0.0, 0.0, 0.0, 0.0, 0.18770781122895494,...
98     [0.1476547764675184, 0.213967226142571, 0.0, 0...
99     [0.0, 0.36665557827010714, 0.0, 0.0, 0.0, 0.0,...
100    [0.0, 0.20441196102344955, 0.0, 0.153775164226...
Name: tfidf, Length: 101, dtype: object

In [47]:
y

0      Classes
1         GOOD
2          BAD
3          BAD
4          BAD
        ...
96     NEUTRAL
97        GOOD
98         BAD
99         BAD
100        BAD
Name: Classes, Length: 101, dtype: object

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [50]:
len(X_train)

80

In [51]:
len(X_test)

21

In [52]:
from sklearn.tree import DecisionTreeClassifier

In [53]:
clf = DecisionTreeClassifier().fit(X_train, y_train)

ValueError: setting an array element with a sequence.