In [1]:
# all imports will be in this cell 

import pandas as pd
import string
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')
porter_stemmer=PorterStemmer()
wordnet_lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\George\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\George\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
data2=pd.read_excel("merged_stock_market.xlsx")
data2

                                                    Text
0       Victoria's Secret & Co. Shares Surge 7% on Q1...
1       HP Gains on Q2 Earnings Beat and Raise\n\nBy ...
2      © Reuters Salesforce Shares Jump 6% on Q1 Earn...
3       HP Inc Earnings, Revenue Beat in Q2\n\nBy Yas...
4       FILE PHOTO: The logo of Swiss bank Credit Sui...
...                                                  ...
66012  By Huw Jones\n\nLONDON (Reuters) - Auditors ar...
66013   FILE PHOTO: A man takes pictures inside a Nor...
66014   Apple Is Raising IPhone 11 Output by Up to 10...
66015  (Bloomberg) -- India stocks erased early gains...
66016   Hong Kong leader invokes emergency powers to ...

[66017 rows x 1 columns]

In [3]:
data2['Text'].dropna(inplace=True)
data2['Text'] = data2['Text'].astype(str)
data

                                                    Text
0       Victoria's Secret & Co. Shares Surge 7% on Q1...
1       HP Gains on Q2 Earnings Beat and Raise\n\nBy ...
2      © Reuters Salesforce Shares Jump 6% on Q1 Earn...
3       HP Inc Earnings, Revenue Beat in Q2\n\nBy Yas...
4       FILE PHOTO: The logo of Swiss bank Credit Sui...
...                                                  ...
66012  By Huw Jones\n\nLONDON (Reuters) - Auditors ar...
66013   FILE PHOTO: A man takes pictures inside a Nor...
66014   Apple Is Raising IPhone 11 Output by Up to 10...
66015  (Bloomberg) -- India stocks erased early gains...
66016   Hong Kong leader invokes emergency powers to ...

[66017 rows x 1 columns]

In [4]:
# helper functions - all helper functions will be reported here

def remove_punctuation(text):
    punctuationfree="".join([i for i in text if i not in string.punctuation])
    return punctuationfree

def tokenization(text):
    tokens = re.split('W+', text)
    return tokens

def remove_stopwords(text):
    output= [i for i in text if not i in stopwords]
    return output

def stemming(text):
    stem_text=[porter_stemmer.stem(word) for word in text]
    return stem_text

def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    return lemm_text

In [5]:
# data preprocess

# remove punctuation from Text column - create a new column 
data2['clean_msg']=data2['Text'].apply(lambda x:remove_punctuation(x))

# lower all letters - create a new column 
data2['msg_lower']=data2['clean_msg'].apply(lambda x: x.lower())

import gensim
data2['no_stopwords']=data2['msg_lower'].apply(gensim.utils.simple_preprocess)

# tokenize all rows - create a new column 
#data['msg_tokenied']= data['msg_lower'].apply(lambda x: tokenization(x))

# remove stopwords - create a new column
data2['no_stopwords2']=data2['no_stopwords'].apply(lambda x:remove_stopwords(x))

# stemme texts - create a new column
data2['msg_stemmed']=data2['no_stopwords2'].apply(lambda x:stemming(x))

# lemmatize texts - create a new column
data2['msg_lemmatized']=data2['msg_stemmed'].apply(lambda x:lemmatizer(x))

data2['msg_lemmatized_string']=data2['msg_lemmatized'].apply(lambda x: ' '.join(map(str, x)))

data2.head()

,Text,clean_msg,msg_lower,no_stopwords,no_stopwords2,msg_stemmed,msg_lemmatized,msg_lemmatized_string
0,Victoria's Secret & Co. Shares Surge 7% on Q1...,Victorias Secret Co Shares Surge 7 on Q1 Ear...,victorias secret co shares surge 7 on q1 ear...,"[victorias, secret, co, shares, surge, on, ear...","[victorias, secret, co, shares, surge, earning...","[victoria, secret, co, share, surg, earn, beat...","[victoria, secret, co, share, surg, earn, beat...",victoria secret co share surg earn beat davit ...
1,HP Gains on Q2 Earnings Beat and Raise\n\nBy ...,HP Gains on Q2 Earnings Beat and Raise\n\nBy ...,hp gains on q2 earnings beat and raise\n\nby ...,"[hp, gains, on, earnings, beat, and, raise, by...","[hp, gains, earnings, beat, raise, davit, kira...","[hp, gain, earn, beat, rais, davit, kirakosyan...","[hp, gain, earn, beat, rais, davit, kirakosyan...",hp gain earn beat rais davit kirakosyan hp inc...
2,© Reuters Salesforce Shares Jump 6% on Q1 Earn...,© Reuters Salesforce Shares Jump 6 on Q1 Earni...,© reuters salesforce shares jump 6 on q1 earni...,"[reuters, salesforce, shares, jump, on, earnin...","[reuters, salesforce, shares, jump, earnings, ...","[reuter, salesforc, share, jump, earn, beat, d...","[reuter, salesforc, share, jump, earn, beat, d...",reuter salesforc share jump earn beat davit ki...
3,"HP Inc Earnings, Revenue Beat in Q2\n\nBy Yas...",HP Inc Earnings Revenue Beat in Q2\n\nBy Yasi...,hp inc earnings revenue beat in q2\n\nby yasi...,"[hp, inc, earnings, revenue, beat, in, by, yas...","[hp, inc, earnings, revenue, beat, yasin, ebra...","[hp, inc, earn, revenu, beat, yasin, ebrahim, ...","[hp, inc, earn, revenu, beat, yasin, ebrahim, ...",hp inc earn revenu beat yasin ebrahim investin...
4,FILE PHOTO: The logo of Swiss bank Credit Sui...,FILE PHOTO The logo of Swiss bank Credit Suis...,file photo the logo of swiss bank credit suis...,"[file, photo, the, logo, of, swiss, bank, cred...","[file, photo, logo, swiss, bank, credit, suiss...","[file, photo, logo, swiss, bank, credit, suiss...","[file, photo, logo, swiss, bank, credit, suiss...",file photo logo swiss bank credit suiss seen h...

In [ ]:
#exw to kainourgio dataset apo panw(step-1)
#vectorizer=v
#classifier=clf(oti exw stin kathe periptwsh)
X_new=vectorizer.transform(data['msg_lemmatized_string'])
#mporw na to arxikopoihsw se metablhth kai meta na kanw data.apply gia na efarmostei se olo ton pinaka
classifier.predict(X_new)